# Generated by Django 5.1.1 on 2024-09-25 14:14

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=63, verbose_name="식당 이름")),
                (
                    "address",
                    models.CharField(max_length=1023, verbose_name="식당 주소"),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=127,
                        null=True,
                        verbose_name="식당 상세 주소",
                    ),
                ),
                ("longitude", models.FloatField(verbose_name="경도")),
                ("latitude", models.FloatField(verbose_name="위도")),
                (
                    "far_from_lions_park",
                    models.FloatField(db_index=True, verbose_name="라팍과의 직선 거리"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("KOREAN", "한식"),
                            ("JAPANESE", "일식"),
                            ("CHINESE", "중식"),
                            ("WESTERN_FOOD", "양식"),
                            ("MEAT", "고기"),
                            ("FRIED_CHICKEN", "치킨"),
                            ("CHICKEN", "닭요리"),
                        ],
                        max_length=63,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(max_length=63, verbose_name="작성자 IP"),
                ),
                (
                    "players_pick",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="이 가게를 고른 선수 이름",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("post", models.TextField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.restaurant",
                        verbose_name="식당 id",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
