# Generated by Django 5.1.1 on 2024-09-26 15:08

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.CharField(
                choices=[
                    ("KOREAN", "한식"),
                    ("JAPANESE", "일식"),
                    ("CHINESE", "중식"),
                    ("WESTERN_FOOD", "양식"),
                    ("MEAT", "고기"),
                    ("FRIED_CHICKEN", "치킨"),
                    ("CHICKEN", "닭요리"),
                    ("FISH", "물고기"),
                    ("DRINK", "술집"),
                    ("CAFE", "카페"),
                ],
                max_length=63,
                verbose_name="카테고리",
            ),
        ),
        migrations.CreateModel(
            name="RestaurantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("img_url", models.URLField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="restaurants.restaurant",
                        verbose_name="식당 id",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
