# Generated by Django 5.1.1 on 2024-09-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_category_restaurantimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantimage",
            name="img_url",
            field=models.URLField(max_length=4095),
        ),
    ]
