# Generated by Django 5.1.1 on 2024-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_restaurantimage_img_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={},
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="detail_address",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="식당 상세 주소"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["category", "far_from_lions_park"],
                name="restaurants_categor_e42e8e_idx",
            ),
        ),
    ]
