# Generated by Django 5.1.1 on 2024-09-28 04:03

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="답변 받을 이메일"
                    ),
                ),
                (
                    "bug_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT_NOT_FOUND", "식당을 찾을 수 없어요."),
                            ("WRONG_RESTAURANT_IMAGE", "식당 이미지들이 이상해요."),
                            ("ADVERTISEMENT_DOUBT", "광고가 의심돼요."),
                        ],
                        max_length=127,
                        verbose_name="버그 유형",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[("REPORTED", "제보 완료"), ("DONE", "조치 완료")],
                        max_length=127,
                        verbose_name="버그 상태 유형",
                    ),
                ),
                ("title", models.CharField(max_length=63, verbose_name="제목")),
                ("description", models.CharField(max_length=1023, verbose_name="내용")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("answer", models.CharField(max_length=1023, verbose_name="처리 내용")),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="bugs.bug",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
