# Generated by Django 5.1.1 on 2024-09-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="bug_type",
            field=models.CharField(
                choices=[
                    ("RESTAURANT_NOT_FOUND", "식당을 찾을 수 없어요."),
                    ("WRONG_RESTAURANT_IMAGE", "식당 이미지들이 이상해요."),
                    ("ADVERTISEMENT_DOUBT", "광고가 의심돼요."),
                    ("NOT_RESTAURANT_PLACE", "이 장소는 식당이 아니에요."),
                    ("SERVICE_NOT_WORKED", "서비스가 정상 동작하지 않아요."),
                ],
                max_length=127,
                verbose_name="버그 유형",
            ),
        ),
    ]
